### ISSUE TITLE
✨ LibSort

### ISSUE THREAD

**Issue by raxhvl** [Vectorized/soledge#15]
Port LibSort from solady as part of #7.

**Comment by atarpara** [comment]
@raxhvl, could you please explain which parts of `LibSort` benefit from the new opcodes (such as `mcopy`, `tstore`, `tload`, `push0`, etc.)? We're trying to avoid moving all files from `solady` because it's a hassle to upstream new commits from `solady` to `soledge`.

**Comment by Vectorized** [comment]
I'm leaving this one on hold first. LibSort only has a single copy function.

I think DynamicBufferLib will benefit most from `mcopy`, as it is literally copying.

**Comment by Vectorized** [comment]
Actually, I'd prefer if there is a library called `MemCopyLib` instead of `LibSort`.

It will have functions for copying memory arrays and bytes.

**Comment by raxhvl** [comment]
> could you please explain which parts of LibSort 

@atarpara was hoping to use `mcopy` in `LibSort.copy()` - seemed like a gentle start for me.

>  because it's a hassle to upstream new commits from solady

I can imagine the pain. On a separate note, how are you folks planning to tackle that?  

> I'm leaving this one on hold first. LibSort only has a single copy function.

Should I close (PR + Issue) for now?

> I think DynamicBufferLib will benefit most from mcopy, as it is literally copying.

I will start with this.

> It will have functions for copying memory arrays and bytes.

And then this.

**Comment by atarpara** [comment]
> Should I close (PR + Issue) for now?

Yes you can close both.
